- name: Setup
  hosts: all
  tags: setup
  roles:
    - { role: geerlingguy.docker, become: yes }
  tasks:
    - name: Ignore PEP 668 because it's silly.
      ansible.builtin.file:
        path: /usr/lib/python3.12/EXTERNALLY-MANAGED
        state: absent
      become: true

    - name: Install pip
      apt:
        name: python3-pip
        update_cache: yes
        cache_valid_time: 604800
      become: true

    - name: Install docker python lib
      pip:
        name: docker

